
/* This file was automatically generated by "gen_wave.py".
   (C) 2014 Christophe Jacquet.
   (C) 2023 Anthony96922.
   (C) 2025 kuba201.
   Released under the GNU GPL v3 license.
*/

float waveform_biphase[4] = {0.0, 1.0, 1.2246467991473532e-16, -1.0};

